name: Build and publish Rust package

on:
    push:
      tags:
        - 'rust-v*'
  
  jobs:
    publish:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
  
        - name: Cache cargo dependencies
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              rust/target
            key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
            restore-keys: |
              ${{ runner.os }}-cargo-
  
        - name: Run tests
          working-directory: rust
          run: cargo test --verbose
  
        - name: Build release
          working-directory: rust
          run: cargo build --release --verbose
  
        - name: Publish to crates.io
          working-directory: rust
          env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          run: cargo publish